dataset:
  train: "c:/Users/Igor/Documents/Trabalho de ALN/dataset/train"
  valid: "c:/Users/Igor/Documents/Trabalho de ALN/dataset/valid"

model:
  architecture: "ResNet50"  # Example architecture, can be changed
  input_shape: [100, 100, 3]  # Image dimensions
  num_classes: 5  # Adjust based on the number of classes in your dataset

training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  validation_split: 0.2

logging:
  log_dir: "logs/"
  log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

augmentation:
  horizontal_flip: true
  rotation_range: 20
  zoom_range: 0.2
  width_shift_range: 0.1
  height_shift_range: 0.1

evaluation:
  metrics: ["accuracy", "precision", "recall"]